// Seed the shared system-exercise library (SPEC.md §9.1). System exercises have
// `isSystem = true` and `ownerId = null`; they are readable by every user and
// read-only (an "edit" clones an owned copy — Milestone 3).
//
// Idempotent: re-running updates all fields for existing exercises so it also
// serves as the migration path when muscle groups are refined.
//
// Run with `npx prisma db seed` (wired in prisma.config.ts) or `npm run db:seed`.

import "dotenv/config";

import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

import { PrismaClient } from "../src/generated/prisma/client";
import type { Equipment, MuscleGroup } from "../src/lib/constants";

type SeedExercise = {
  name: string;
  equipment: Equipment;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles?: MuscleGroup[];
  description?: string;
  instructions?: string;
  commonPitfalls?: string;
};

const SYSTEM_EXERCISES: SeedExercise[] = [
  // ─── Barbell ──────────────────────────────────────────────────────────────
  {
    name: "Barbell Bench Press",
    equipment: "BARBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "FRONT_DELTS"],
    description: "Classic pressing movement; the primary chest builder.",
    instructions: "Lie flat on bench, grip bar slightly wider than shoulder-width. Unrack and lower bar to mid-chest under control. Press back up to full extension.",
    commonPitfalls: "Bouncing the bar off the chest. Flaring elbows too wide (90°). Lifting hips off the bench. Using too much weight before mastering form.",
  },
  {
    name: "Barbell Back Squat",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    description: "Compound leg movement; heavy quad focus with posterior chain involvement.",
    instructions: "Position bar on upper traps, feet shoulder-width apart. Brace core, push knees out, descend until hips are below parallel. Drive through heels to stand.",
    commonPitfalls: "Knees caving inward (valgus collapse). Heels rising (fix: raise heels on plates or work ankle mobility). Forward torso lean. Squatting to depth without hip flexibility.",
  },
  {
    name: "Barbell Deadlift",
    equipment: "BARBELL",
    primaryMuscles: ["GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["LOWER_BACK", "QUADS"],
    description: "Full-body compound; the ultimate posterior chain builder.",
    instructions: "Stand with bar over mid-foot, hip-width stance. Hinge at hips, grip just outside legs. Brace, then drive floor away while keeping bar close. Lock out hips and knees together.",
    commonPitfalls: "Rounding the lower back under load. Bar drifting away from legs. Jerking the bar off the floor. Hyperextending at lockout.",
  },
  {
    name: "Barbell Bent-Over Row",
    equipment: "BARBELL",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["BICEPS", "LATS"],
    description: "Classic back thickness builder; compound pulling movement.",
    instructions: "Hinge forward ~45°, bar hanging from fully extended arms. Row bar to lower chest/navel by driving elbows back and up. Lower under control.",
    commonPitfalls: "Using too much body English / momentum. Raising torso on each rep. Pulling to the wrong part of the torso. Letting shoulder blades flare instead of retracting.",
  },
  {
    name: "Barbell Overhead Press",
    equipment: "BARBELL",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS", "REAR_DELTS"],
    description: "Standing overhead press; primary shoulder strength developer.",
    instructions: "Stand, grip bar just outside shoulders. Press bar straight up, pushing head through at the top. Lower back to clavicle under control.",
    commonPitfalls: "Excessive lower-back arch. Bar path drifting forward. Not locking out elbows at the top. Performing a slow push press instead of a strict press.",
  },
  {
    name: "Barbell Curl",
    equipment: "BARBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    description: "Isolation bicep exercise; classic arm builder.",
    instructions: "Stand, underhand grip shoulder-width. Keeping upper arms stationary, curl bar to shoulder height. Squeeze biceps at top, lower slowly.",
    commonPitfalls: "Swinging the torso to initiate each rep. Upper arms drifting forward. Dropping the weight on the way down instead of lowering with control.",
  },
  {
    name: "Barbell Incline Bench Press",
    equipment: "BARBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS", "TRICEPS"],
    description: "Incline pressing; upper chest and front delt emphasis.",
    instructions: "Set bench to 30–45° incline. Press bar from upper chest to full extension. Lower to chest.",
    commonPitfalls: "Incline too steep causing shoulder impingement. Bar path drifting forward. Excessive arch.",
  },
  {
    name: "Barbell Front Squat",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "ABS"],
    description: "Front rack squat; upright quad-dominant movement.",
    instructions: "Bar across front delts and shoulders. Squat to depth keeping torso upright. Drive through heels.",
    commonPitfalls: "Elbows dropping forward. Excessive forward lean. Bar rolling off shoulders.",
  },
  {
    name: "Barbell Romanian Deadlift",
    equipment: "BARBELL",
    primaryMuscles: ["HAMSTRINGS", "LOWER_BACK"],
    secondaryMuscles: ["GLUTES"],
    description: "Hip hinge with straight legs; posterior chain stretch and strength.",
    instructions: "Bar in hands at thigh level, slight knee bend. Hinge at hips, lowering bar down shins while keeping torso straight. Return to standing.",
    commonPitfalls: "Rounding the lower back. Excessive knee bend. Not feeling the hamstring stretch.",
  },
  {
    name: "Barbell Pendlay Row",
    equipment: "BARBELL",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["BICEPS", "LATS"],
    description: "Explosive chest-supported row; power and thickness.",
    instructions: "Bend to 45°, bar touching chest. Drive bar explosively into your chest. Control the descent.",
    commonPitfalls: "Using too much momentum. Hyperextending at the top. Insufficient chest support.",
  },
  {
    name: "Barbell Sumo Deadlift",
    equipment: "BARBELL",
    primaryMuscles: ["GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["QUADS", "LOWER_BACK", "ADDUCTORS"],
    description: "Wide-stance deadlift; glute and inner thigh emphasis.",
    instructions: "Wider than shoulder-width stance, toes out 30°. Bar over mid-foot. Drive floor away to lockout.",
    commonPitfalls: "Knees not tracking toes. Heels raising. Bar drifting away from body.",
  },
  {
    name: "Barbell Hack Squat (on machine or with bar)",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES"],
    description: "Machine squat variation; quad isolation with reduced lower back stress.",
    instructions: "On machine or behind back with bar. Squat to depth. Press through midfoot to stand.",
    commonPitfalls: "Knees caving. Heels rising. Not reaching full depth.",
  },
  {
    name: "Barbell Good Morning",
    equipment: "BARBELL",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["HAMSTRINGS", "GLUTES"],
    description: "Back hyperextension with bar; posterior chain strength.",
    instructions: "Bar on shoulders. Hinge forward to 45° keeping legs straight. Return to standing.",
    commonPitfalls: "Rounding the lower back excessively. Using too much weight. Jerky movement.",
  },
  {
    name: "Barbell Leg Press",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    description: "Machine leg press variations; quad-dominant pressing.",
    instructions: "Load bar on machine, feet on platform. Lower bar to knees. Press to extension.",
    commonPitfalls: "Knees caving. Hips lifting off. Insufficient depth.",
  },
  {
    name: "Barbell Calf Raise",
    equipment: "BARBELL",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: [],
    description: "Free-weight calf raise; loaded gastrocnemius work.",
    instructions: "Bar on shoulders, feet hip-width. Rise up onto balls of feet. Lower with control.",
    commonPitfalls: "Not achieving full range. Using momentum. Insufficient weight.",
  },

  // ─── Dumbbell ─────────────────────────────────────────────────────────────
  {
    name: "Dumbbell Bench Press",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "FRONT_DELTS"],
    description: "Dumbbells allow a greater range of motion than barbell pressing.",
    instructions: "Lie on bench, dumbbells at chest level. Press up and slightly inward until arms are fully extended. Lower with control, allowing a slight stretch at the bottom.",
    commonPitfalls: "Letting the dumbbells drift too far apart at the top. Losing shoulder stability by going too heavy. Not getting the full stretch at the bottom.",
  },
  {
    name: "Dumbbell Rows",
    equipment: "DUMBBELL",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["BICEPS", "LATS"],
    description: "One-arm rows; unilateral back and lat development.",
    instructions: "Place one knee and hand on bench. Hold dumbbell in opposite hand. Row dumbbell to hip/lower rib, driving elbow back. Keep torso flat.",
    commonPitfalls: "Rotating the torso (using rotation rather than the lat). Shrugging the shoulder at the top instead of retracting the scapula. Pulling toward the shoulder rather than the hip.",
  },
  {
    name: "Dumbbell Shoulder Press",
    equipment: "DUMBBELL",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS"],
    description: "Bilateral shoulder pressing with dumbbells; stability challenge.",
    instructions: "Seated or standing, hold dumbbells at ear height with elbows at 90°. Press directly overhead to full extension. Lower back to start.",
    commonPitfalls: "Pressing the dumbbells forward rather than directly up. Arching the lower back excessively. Not fully extending at the top.",
  },
  {
    name: "Dumbbell Flyes",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Isolation chest movement; excellent pec stretch and activation.",
    instructions: "Lie on bench, dumbbells extended above chest with slight bend in elbows. Lower arms in a wide arc until chest stretches. Squeeze pecs to bring dumbbells back together.",
    commonPitfalls: "Bending elbows too much (turns into a press). Going so heavy the shoulder joint is stressed. Locking elbows straight.",
  },
  {
    name: "Dumbbell Curls",
    equipment: "DUMBBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    description: "Classic arm isolation; two-arm bicep builder.",
    instructions: "Stand or sit, dumbbells hanging at sides. Curl both dumbbells (or alternate) to shoulder height with palms facing up. Lower with control.",
    commonPitfalls: "Wrist deviation at the top. Swinging the weights up. Not supinating (rotating palm up) during the lift.",
  },
  {
    name: "Dumbbell Lateral Raise",
    equipment: "DUMBBELL",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRAPS"],
    description: "Side delt isolation; crucial for shoulder width.",
    instructions: "Hold dumbbells at sides. Raise arms out to the side to shoulder height, leading with elbows, thumbs slightly down. Lower slowly.",
    commonPitfalls: "Using too much weight and shrugging traps to lift. Raising arms above shoulder height. Swinging the dumbbells rather than a controlled raise.",
  },
  {
    name: "Dumbbell Goblet Squat",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Unloaded squat variation; mobility and leg development.",
    instructions: "Hold a dumbbell vertically at chest height. Squat with feet slightly wider than shoulder-width. Descend between knees to depth, keeping chest tall. Drive through heels to stand.",
    commonPitfalls: "Letting elbows cave inward. Heels rising off the floor. Rounding the upper back. Not reaching full depth.",
  },
  {
    name: "Dumbbell Tricep Extension",
    equipment: "DUMBBELL",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    description: "Overhead tricep isolation; lockout strength builder.",
    instructions: "Hold one dumbbell overhead with both hands. Keeping upper arms vertical, lower the dumbbell behind your head. Extend back to full lockout.",
    commonPitfalls: "Flaring elbows out to the side. Moving upper arms rather than only bending at the elbow. Using too heavy a weight and losing range of motion.",
  },
  {
    name: "Dumbbell Incline Bench Press",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS", "TRICEPS"],
    description: "Incline dumbbell pressing; upper chest development.",
    instructions: "On incline bench, press dumbbells from shoulder level. Full extension, lower with control.",
    commonPitfalls: "Dumbbells drifting too wide. Losing shoulder stability. Not getting the full stretch.",
  },
  {
    name: "Dumbbell Decline Bench Press",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS"],
    description: "Decline dumbbell pressing; lower chest emphasis.",
    instructions: "On decline bench, press dumbbells from chest. Press to full extension.",
    commonPitfalls: "Dumbbells too wide. Letting dumbbells drift too far back. Lacking control.",
  },
  {
    name: "Dumbbell Romanian Deadlift",
    equipment: "DUMBBELL",
    primaryMuscles: ["HAMSTRINGS", "LOWER_BACK"],
    secondaryMuscles: ["GLUTES"],
    description: "Single-leg or bilateral RDL; hamstring and lower back strength.",
    instructions: "Dumbbells in hands, slight knee bend. Hinge at hips, lowering dumbbells to shins. Return to standing.",
    commonPitfalls: "Rounding the lower back. Excessive knee bend. Not feeling hamstring engagement.",
  },
  {
    name: "Dumbbell Bulgarian Split Squat",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Single-leg squat variation; balance and unilateral strength.",
    instructions: "Rear foot elevated on bench, front foot forward. Holding dumbbells, lower front knee to 90°. Press to stand.",
    commonPitfalls: "Front knee tracking over toes (should be behind). Leaning too far forward. Stepping too close to bench.",
  },
  {
    name: "Dumbbell Pullover",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["LATS", "FRONT_DELTS"],
    description: "Chest and lat stretching movement; unique range of motion.",
    instructions: "Perpendicular to bench, upper back on bench. Dumbbell above chest with slight bend. Lower over and behind you in an arc. Return.",
    commonPitfalls: "Arms bending too much. Not getting the full stretch. Using too heavy a weight.",
  },
  {
    name: "Dumbbell Renegade Row",
    equipment: "DUMBBELL",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["CHEST", "ABS", "BICEPS"],
    description: "Plank-position rowing; core and back integration.",
    instructions: "High plank on dumbbells. Row one dumbbell to hip while stabilizing with other arm. Alternate sides.",
    commonPitfalls: "Hips rotating or dropping. Dumbbells moving. Using too heavy a weight and losing stability.",
  },
  {
    name: "Dumbbell Alternating Curl",
    equipment: "DUMBBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    description: "Alternating bicep curl; unilateral arm development.",
    instructions: "Dumbbells at sides. Curl one dumbbell to shoulder while rotating forearm. Alternate arms.",
    commonPitfalls: "Wrist deviation. Using momentum. Not achieving full range of motion.",
  },
  {
    name: "Dumbbell Hammer Curls",
    equipment: "DUMBBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    description: "Neutral-grip curls; brachialis and bicep development.",
    instructions: "Dumbbells at sides, neutral grip (palms facing each other). Curl to shoulder height. Lower with control.",
    commonPitfalls: "Rotating the wrist during the curl. Using momentum. Letting elbows drift forward.",
  },
  {
    name: "Dumbbell Kickbacks",
    equipment: "DUMBBELL",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    description: "Tricep isolation; arm finisher.",
    instructions: "Bent over 45°, elbow bent at 90°. Extend arm straight back by contracting triceps. Return to 90°.",
    commonPitfalls: "Using momentum to swing. Elbows rising. Using too much weight and losing the squeeze.",
  },
  {
    name: "Dumbbell Overhead Carry",
    equipment: "DUMBBELL",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["ABS", "TRAPS"],
    description: "Loaded carry; shoulder stability and core strength.",
    instructions: "Hold dumbbell overhead with one arm, locked out. Walk for distance, keeping core tight.",
    commonPitfalls: "Dumbbell drifting forward. Leaning away to compensate. Shoulder dropping.",
  },
  {
    name: "Dumbbell Step-ups",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Single-leg stepping movement; unilateral leg development.",
    instructions: "Hold dumbbells, step onto bench with front leg. Drive through front heel to stand. Lower back down.",
    commonPitfalls: "Not using front leg power. Leaning forward. Knee valgus collapse.",
  },
  {
    name: "Dumbbell Calf Raises",
    equipment: "DUMBBELL",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: [],
    description: "Dumbbell loaded calf raises; portable calf training.",
    instructions: "Hold dumbbells at sides, feet hip-width. Rise onto toes. Lower slowly.",
    commonPitfalls: "Not achieving full range. Losing balance. Momentum instead of control.",
  },
  {
    name: "Sumo Goblet Squat",
    equipment: "DUMBBELL",
    primaryMuscles: ["ADDUCTORS"],
    secondaryMuscles: ["QUADS", "GLUTES"],
    description: "Wide-stance goblet squat; inner thigh and quad focus.",
    instructions: "Hold dumbbell at chest, feet wider than shoulder-width with toes pointed out 45°. Squat deep, keeping chest tall and knees tracking over toes. Drive through heels to stand.",
    commonPitfalls: "Knees collapsing inward. Heels rising. Torso folding forward. Not reaching depth.",
  },

  // ─── Machine ──────────────────────────────────────────────────────────────
  {
    name: "Leg Press",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    description: "Lower body pressing machine; heavy quad focus.",
    instructions: "Sit in machine, feet shoulder-width on platform. Lower platform by bending knees toward chest, stopping before hips lift. Press to near-full extension.",
    commonPitfalls: "Locking knees out completely at the top (risk to joint). Allowing hips to lift off the seat (lower back rounding). Feet placement too high or too low.",
  },
  {
    name: "Chest Press Machine",
    equipment: "MACHINE",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS"],
    description: "Guided pressing movement; stable chest development.",
    instructions: "Adjust seat so handles are at chest height. Grip handles and press forward to near-full arm extension. Return under control.",
    commonPitfalls: "Arching the lower back off the pad. Allowing the weight stack to crash on return. Gripping too wide causing shoulder discomfort.",
  },
  {
    name: "Lat Pulldown",
    equipment: "MACHINE",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "UPPER_BACK"],
    description: "Vertical pulling machine; lat width and back thickness.",
    instructions: "Sit with knees under pads, grip bar wider than shoulders. Pull bar to upper chest by driving elbows down and back. Squeeze lats. Return with control.",
    commonPitfalls: "Leaning back too far (becomes a row). Pulling behind the neck (cervical risk). Using momentum to jerk the weight down.",
  },
  {
    name: "Leg Curl",
    equipment: "MACHINE",
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: ["GLUTES"],
    description: "Hamstring isolation; knee flexion movement.",
    instructions: "Lie face down on machine, pad resting just above heels. Curl legs toward glutes through full range. Lower slowly.",
    commonPitfalls: "Hips rising off the pad (reduces hamstring isolation). Partial range of motion. Letting the weight drop quickly on the way down.",
  },
  {
    name: "Leg Extension",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: [],
    description: "Quadriceps isolation; knee extension machine.",
    instructions: "Sit in machine, pad resting on shins just above ankles. Extend legs to full knee extension. Lower slowly without letting the stack touch.",
    commonPitfalls: "Using excessive weight that causes knee strain. Lifting hips off the seat. Not controlling the eccentric (lowering) phase.",
  },
  {
    name: "Shoulder Press Machine",
    equipment: "MACHINE",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS"],
    description: "Seated or standing shoulder press; controlled overhead pressing.",
    instructions: "Adjust seat so handles are at shoulder height. Press upward to full extension without locking elbows. Lower to start.",
    commonPitfalls: "Seat too low causing shoulder impingement. Pressing to full lockout and stressing the joint. Using momentum to push the weight up.",
  },
  {
    name: "Hack Squat Machine",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES"],
    description: "Machine-guided squat; reduced balance demand.",
    instructions: "Back and shoulders on pads, feet shoulder-width on platform. Lower until knees are at 90°. Press to stand.",
    commonPitfalls: "Knees caving inward. Heels rising. Not reaching full depth.",
  },
  {
    name: "Smith Machine Bench Press",
    equipment: "MACHINE",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "FRONT_DELTS"],
    description: "Smith machine pressing; stability aid for free-weight movements.",
    instructions: "Adjust bar to chest height. Unrack and press to full extension. Lower under control.",
    commonPitfalls: "Bar path not vertical (using the rails incorrectly). Excessive arch. Uncontrolled descent.",
  },
  {
    name: "Pendulum Squat",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Pendulum machine movement; hip-friendly leg press variation.",
    instructions: "Sit in machine, feet on platform. Lower by bending knees. Press to near-full extension.",
    commonPitfalls: "Hip position too high or low. Knees tracking inward. Using excessive weight.",
  },
  {
    name: "V-Squat Machine",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    description: "Angled squat machine; unique movement angle.",
    instructions: "Position in machine with shoulders on pads. Squat to depth. Press to standing.",
    commonPitfalls: "Not reaching adequate depth. Knees caving. Uneven weight distribution.",
  },
  {
    name: "Seated Leg Press",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    description: "Seated leg pressing machine; quad and lower body focus.",
    instructions: "Sit in machine, feet on platform at shoulder-width. Push away to near-full extension. Lower with control.",
    commonPitfalls: "Locking knees at the top. Hips lifting off the seat. Feet placed too high or too low.",
  },
  {
    name: "Seated Calf Raise Machine",
    equipment: "MACHINE",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: [],
    description: "Isolated calf machine; soleus emphasis.",
    instructions: "Sit in machine, balls of feet on platform, knees under pads. Raise heels up. Lower with control.",
    commonPitfalls: "Not getting full range of motion. Using momentum. Insufficient weight.",
  },
  {
    name: "Standing Calf Raise Machine",
    equipment: "MACHINE",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: [],
    description: "Standing calf machine; gastrocnemius emphasis.",
    instructions: "Stand under pads, balls of feet on platform. Rise up on toes. Lower with control.",
    commonPitfalls: "Not achieving full range. Using momentum. Allowing knees to bend.",
  },
  {
    name: "Machine Back Hyper Extension",
    equipment: "MACHINE",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["HAMSTRINGS", "GLUTES"],
    description: "Lower back extension machine; posterior chain strengthening.",
    instructions: "Position torso on machine, legs extended. Raise torso up at the hips. Lower back to start.",
    commonPitfalls: "Hyperextending beyond neutral. Using momentum. Not achieving full range.",
  },
  {
    name: "Machine Chest Fly",
    equipment: "MACHINE",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Machine chest isolation; constant tension fly.",
    instructions: "Sit upright, handles at chest height. Bring handles together in front of chest. Return slowly.",
    commonPitfalls: "Letting handles go too far back. Leaning back excessively. Using momentum.",
  },
  {
    name: "Hip Adductor Machine",
    equipment: "MACHINE",
    primaryMuscles: ["ADDUCTORS"],
    secondaryMuscles: [],
    description: "Inner thigh isolation; adductor strength and hip stability.",
    instructions: "Sit in machine, legs placed outside the pads. Squeeze legs together against resistance. Return slowly to start.",
    commonPitfalls: "Using too much weight and recruiting the hip flexors. Not getting full range of motion. Releasing too fast on the eccentric.",
  },
  {
    name: "Hip Abduction Machine",
    equipment: "MACHINE",
    primaryMuscles: ["ABDUCTORS"],
    secondaryMuscles: [],
    description: "Outer thigh isolation; abductor and glute med strength.",
    instructions: "Sit in machine, legs placed inside the pads. Push legs outward against resistance. Return slowly to start.",
    commonPitfalls: "Leaning the torso to compensate. Using momentum. Insufficient range of motion.",
  },
  {
    name: "Reverse Hyperextension",
    equipment: "MACHINE",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["GLUTES"],
    description: "Posterior chain decompression exercise; lower back and glute activation.",
    instructions: "Lie face-down on the machine pad with hips at the edge. Swing legs up by extending at the hips. Lower with control.",
    commonPitfalls: "Using momentum rather than hip extension. Hyperextending the lower back at the top. Going too heavy too soon.",
  },

  // ─── Cable ────────────────────────────────────────────────────────────────
  {
    name: "Cable Chest Flyes",
    equipment: "CABLE",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Constant tension chest isolation; pec pump.",
    instructions: "Set cables at shoulder height. Stand in the middle and hold handles with arms slightly bent. Bring hands together in front of chest in a hugging arc. Return with control.",
    commonPitfalls: "Straightening the arms (turning into a press). Letting the cables pull arms too far back past the chest line. Leaning too far forward.",
  },
  {
    name: "Cable Rows",
    equipment: "CABLE",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["BICEPS", "LATS"],
    description: "Horizontal pulling cable movement; back and lat development.",
    instructions: "Sit at cable row station, feet on platform. Pull handle to abdomen by driving elbows back and squeezing shoulder blades. Keep torso upright.",
    commonPitfalls: "Rocking the torso forward and back with each rep. Shrugging shoulders instead of retracting scapulae. Pulling to the wrong height.",
  },
  {
    name: "Cable Bicep Curls",
    equipment: "CABLE",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    description: "Constant tension bicep isolation; full range activation.",
    instructions: "Stand at low cable, underhand grip on bar or rope. Keeping elbows at sides, curl to shoulder height. Squeeze biceps at top. Lower slowly.",
    commonPitfalls: "Pulling elbows forward during the curl. Using body swing. Not fully extending at the bottom to take advantage of constant cable tension.",
  },
  {
    name: "Cable Tricep Pushdown",
    equipment: "CABLE",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    description: "Tricep isolation at the cable stack; arm finisher.",
    instructions: "Stand at high cable with rope or bar. Tuck elbows to sides. Extend arms fully downward by contracting triceps. Return to 90° at elbows.",
    commonPitfalls: "Allowing elbows to flare and drift forward. Leaning heavily over the cable. Not achieving full extension at the bottom.",
  },
  {
    name: "Cable Lateral Raise",
    equipment: "CABLE",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRAPS"],
    description: "Cable side delt isolation; constant tension raise.",
    instructions: "Stand with cable on one side, handle at waist. Raise arm out to shoulder height. Lower slowly.",
    commonPitfalls: "Using too much momentum. Raising arm above shoulder. Shrugging the shoulder.",
  },
  {
    name: "Cable Kickback",
    equipment: "CABLE",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    description: "Tricep isolation via cable; consistent resistance.",
    instructions: "Face machine, single handle attachment at lower pulley. Hinge at hips slightly, elbow bent. Extend arm back.",
    commonPitfalls: "Elbows rising. Using momentum. Not achieving full range.",
  },
  {
    name: "Cable Woodchop",
    equipment: "CABLE",
    primaryMuscles: ["OBLIQUES", "ABS"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Rotational core movement; anti-rotation stability.",
    instructions: "Stand perpendicular to cable at chest height. Rotate torso, bringing handle across your body. Return with control.",
    commonPitfalls: "Using momentum instead of core rotation. Feet staying planted. Excessive lumbar rotation.",
  },
  {
    name: "Cable Pallof Press",
    equipment: "CABLE",
    primaryMuscles: ["ABS", "OBLIQUES"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Anti-rotational core exercise; stability and control.",
    instructions: "Stand perpendicular to cable at chest height. Press handle straight out, resisting rotation. Return.",
    commonPitfalls: "Rotating the torso away from the cable. Not fully extending. Using momentum.",
  },
  {
    name: "Cable Hip Adduction",
    equipment: "CABLE",
    primaryMuscles: ["ADDUCTORS"],
    secondaryMuscles: ["GLUTES"],
    description: "Standing inner thigh isolation; constant tension adductor work.",
    instructions: "Attach ankle cuff to low cable on outside leg. Stand sideways, sweep leg toward and across the body. Return with control.",
    commonPitfalls: "Leaning the torso to assist. Using momentum. Standing too close to the machine.",
  },
  {
    name: "Cable Hip Abduction",
    equipment: "CABLE",
    primaryMuscles: ["ABDUCTORS"],
    secondaryMuscles: [],
    description: "Standing outer thigh isolation; glute med and abductor work.",
    instructions: "Attach ankle cuff to low cable on inside leg. Stand sideways, sweep leg away from the body. Return with control.",
    commonPitfalls: "Leaning the torso to assist. Using momentum. Insufficient range of motion.",
  },

  // ─── Kettlebell ───────────────────────────────────────────────────────────
  {
    name: "Kettlebell Swing",
    equipment: "KETTLEBELL",
    primaryMuscles: ["GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["LOWER_BACK", "FRONT_DELTS"],
    description: "Explosive hip hinge; posterior chain power and endurance.",
    instructions: "Stand with feet shoulder-width, KB between feet. Hinge hips, grip KB. Drive hips forward explosively to swing KB to shoulder height. Hinge back and repeat.",
    commonPitfalls: "Squatting instead of hinging. Using the arms to lift the kettlebell rather than hip drive. Hyperextending the back at the top.",
  },
  {
    name: "Kettlebell Turkish Get-up",
    equipment: "KETTLEBELL",
    primaryMuscles: ["FRONT_DELTS", "CHEST"],
    secondaryMuscles: ["ABS", "GLUTES"],
    description: "Complex multi-joint movement; full-body strength and stability.",
    instructions: "Lie with KB in one hand extended. Roll to elbow, then hand. Sweep leg through to lunge position. Stand up. Reverse the sequence to return to floor.",
    commonPitfalls: "Rushing the movement. Losing eye contact with the KB at any stage. Not stabilising the shoulder before each transition.",
  },
  {
    name: "Kettlebell Goblet Squat",
    equipment: "KETTLEBELL",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Held kettlebell squat; mobility and depth friendly.",
    instructions: "Hold kettlebell at chest level vertically. Squat to depth with elbows inside knees. Stand up.",
    commonPitfalls: "Letting elbows wing out. Heels rising. Rounding upper back.",
  },
  {
    name: "Kettlebell Suitcase Carry",
    equipment: "KETTLEBELL",
    primaryMuscles: ["OBLIQUES", "ABS"],
    secondaryMuscles: ["TRAPS"],
    description: "Loaded unilateral carry; core and spinal stability.",
    instructions: "Hold kettlebell in one hand at side. Walk for distance, keeping torso upright.",
    commonPitfalls: "Leaning away from the weight. Shoulder dropping. Rotating the torso.",
  },

  // ─── Bodyweight ───────────────────────────────────────────────────────────
  {
    name: "Push-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "FRONT_DELTS"],
    description: "Classic pressing movement; no equipment needed.",
    instructions: "Start in high plank, hands slightly wider than shoulders. Lower chest to floor by bending elbows at ~45°. Push back to full extension.",
    commonPitfalls: "Hips sagging or piking up. Elbows flaring out at 90°. Not reaching full range (partial reps). Head dropping forward.",
  },
  {
    name: "Pull-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "UPPER_BACK"],
    description: "Vertical pulling; compound back and arm builder.",
    instructions: "Hang from bar with overhand grip, shoulder-width. Pull body up by driving elbows down toward hips until chin clears bar. Lower fully.",
    commonPitfalls: "Kipping (swinging) instead of controlled movement. Not fully extending arms at the bottom (dead hang). Shrugging shoulders rather than engaging lats.",
  },
  {
    name: "Dips",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["TRICEPS", "CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Compound pressing movement; chest and arm focus.",
    instructions: "Support on parallel bars with arms extended. Lower body by bending elbows until upper arms are parallel to floor. Press back to full extension.",
    commonPitfalls: "Leaning too far forward (shifts emphasis to chest excessively). Not descending to 90° at the elbow. Locking out elbows violently at the top.",
  },
  {
    name: "Bodyweight Squats",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Leg movement with zero equipment; endurance and form work.",
    instructions: "Feet shoulder-width, toes slightly out. Arms forward for balance. Descend by pushing knees out and hinging hips until thighs are parallel. Stand back up.",
    commonPitfalls: "Knees caving inward. Heels rising. Excessive forward torso lean. Stopping above parallel.",
  },
  {
    name: "Lunges",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Single-leg movement; balance and unilateral leg development.",
    instructions: "Stand tall. Step forward and lower the rear knee toward the floor. Both knees at ~90°. Push through front heel to return to standing.",
    commonPitfalls: "Front knee tracking over toes (should stay behind toes). Torso leaning forward. Taking too short a step. Losing balance by looking down.",
  },
  {
    name: "Planks",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["OBLIQUES"],
    description: "Core isometric hold; stability and endurance.",
    instructions: "Forearms on floor, elbows under shoulders. Feet hip-width. Brace core and glutes to create a straight line from head to heels. Hold.",
    commonPitfalls: "Hips sagging toward the floor. Hips piking up in the air. Holding breath. Neck dropping or raising.",
  },
  {
    name: "Crunches",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: [],
    description: "Isolation abdominal flexion; upper ab focus.",
    instructions: "Lie on back, knees bent, feet flat. Place hands behind ears. Curl shoulders off floor by flexing abs, not pulling the neck. Lower slowly.",
    commonPitfalls: "Pulling on the neck with hands. Using momentum to jerk up. Lifting all the way to a full sit-up (takes load off abs).",
  },
  {
    name: "Chin-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["LATS", "UPPER_BACK"],
    description: "Supinated pull-up; stronger bicep involvement than pull-ups.",
    instructions: "Hang from bar with underhand grip, hands shoulder-width. Pull body up until chin clears the bar. Lower fully to dead hang.",
    commonPitfalls: "Narrow grip causing wrist discomfort. Not achieving full hang at the bottom. Using kipping motion rather than controlled pull.",
  },
  {
    name: "Diamond Push-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: ["CHEST"],
    description: "Hands-together push-up; tricep emphasis.",
    instructions: "Hands close together under chest forming diamond. Lower chest to hands. Press back up.",
    commonPitfalls: "Elbows flaring out. Hips sagging. Partial range of motion.",
  },
  {
    name: "Wide-Grip Push-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Wide-hand push-up; chest and shoulder emphasis.",
    instructions: "Hands wide of shoulders. Lower chest to floor. Press back up.",
    commonPitfalls: "Hands too far apart straining shoulders. Hips sagging. Rushing reps.",
  },
  {
    name: "Pike Push-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS"],
    description: "Elevated hip push-up; shoulder pressing variation.",
    instructions: "High plank with hips raised, body in inverted V. Lower crown of head toward floor. Press back.",
    commonPitfalls: "Hips too low (becomes a regular push-up). Head position forward. Insufficient range.",
  },
  {
    name: "Reverse Grip Chin-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["LATS", "UPPER_BACK"],
    description: "Underhand pull-up; maximum bicep focus.",
    instructions: "Hang underhand, shoulder-width. Pull up until chin clears bar. Lower to dead hang.",
    commonPitfalls: "Narrow grip. Not fully extending at the bottom. Kipping movement.",
  },
  {
    name: "Hanging Leg Raises",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["QUADS"],
    description: "Suspended core exercise; lower ab and hip flexor work.",
    instructions: "Hang from bar. Raise legs to horizontal or higher by contracting abs. Lower slowly.",
    commonPitfalls: "Swinging the legs. Using momentum. Not controlling the descent.",
  },
  {
    name: "Decline Sit-ups",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["QUADS"],
    description: "Decline bench sit-up; heavy abdominal emphasis.",
    instructions: "On decline bench, knees bent, feet anchored. Raise torso to 45–90°. Lower slowly.",
    commonPitfalls: "Jerky movement using momentum. Pulling the neck. Using hip flexors instead of abs.",
  },
  {
    name: "Side Planks",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["OBLIQUES"],
    secondaryMuscles: ["ABS"],
    description: "Lateral core hold; oblique and stability work.",
    instructions: "Side elbow plank on forearm and outer foot. Keep hips level, body in straight line. Hold.",
    commonPitfalls: "Hips dropping or rising. Torso rotating. Holding breath.",
  },
  {
    name: "Superman Holds",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["GLUTES"],
    description: "Prone back extension hold; lower back and glute activation.",
    instructions: "Lie prone, arms extended overhead. Raise chest and legs off floor simultaneously. Hold.",
    commonPitfalls: "Jerky movement. Hyperextending the lower back. Not raising high enough.",
  },
  {
    name: "Glute Bridges",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS", "LOWER_BACK"],
    description: "Supine hip extension; glute activation and strength.",
    instructions: "Lie on back, knees bent, feet under knees. Push through heels to raise hips. Squeeze glutes at top.",
    commonPitfalls: "Using lower back instead of glutes. Not achieving full extension. Feet too far or close.",
  },
  {
    name: "Single-Leg Glute Bridge",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    description: "Unilateral glute exercise; balance and strength development.",
    instructions: "Lie on back, one leg bent, other leg extended. Push through bent leg to raise hips. Hold at top.",
    commonPitfalls: "Hips rotating. Pushing through the extended leg. Not achieving full range.",
  },
  {
    name: "Wall Sits",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES"],
    description: "Isometric quad hold; time under tension leg burner.",
    instructions: "Back against wall, feet shoulder-width, slide down to 90° at knees. Hold position.",
    commonPitfalls: "Knees caving inward. Sliding up. Feet too far from wall.",
  },
  {
    name: "Mountain Climbers",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["FRONT_DELTS"],
    description: "Dynamic plank variation; core and cardiovascular work.",
    instructions: "High plank position. Rapidly drive knees toward chest alternately. Keep hips level.",
    commonPitfalls: "Hips piking up. Bouncing. Touching heels down.",
  },
  {
    name: "Burpees",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CHEST", "QUADS"],
    secondaryMuscles: ["ABS", "FRONT_DELTS"],
    description: "Full-body explosive movement; cardio and strength.",
    instructions: "From standing, drop to push-up position, lower to floor, jump back, stand. Jump at the top.",
    commonPitfalls: "Incomplete push-ups. Lazy landings. Losing form due to fatigue.",
  },
  {
    name: "Copenhagen Plank",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ADDUCTORS"],
    secondaryMuscles: ["ABS"],
    description: "Side plank variation with inner thigh load; adductor strength and hip stability.",
    instructions: "Set up in a side plank with top foot on a bench. Raise hips off the floor and hold. Can be made harder by lifting the bottom leg to meet the top.",
    commonPitfalls: "Hips dropping. Rushing the movement. Insufficient inner thigh engagement.",
  },
  {
    name: "Clamshell",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABDUCTORS"],
    secondaryMuscles: ["GLUTES"],
    description: "Hip abductor isolation; glute med activation and hip stability.",
    instructions: "Lie on your side, hips and knees bent at 45°. Keeping feet together, raise the top knee as high as possible without rotating the pelvis. Lower with control.",
    commonPitfalls: "Pelvis rolling backward during the movement. Not achieving full range. Using too heavy a band if adding resistance.",
  },
  {
    name: "Side-Lying Hip Abduction",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABDUCTORS"],
    secondaryMuscles: [],
    description: "Outer thigh isolation; no equipment required.",
    instructions: "Lie on your side, bottom leg bent for support. Raise the top leg to about 45° keeping toes pointing forward. Lower with control.",
    commonPitfalls: "Rotating the hip so toes point to the ceiling. Using momentum. Not pausing at the top.",
  },
  {
    name: "Back Extension",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["GLUTES"],
    description: "Hyperextension movement; erector spinae and glute activation.",
    instructions: "Position yourself on a hyperextension bench with hips at the top edge. Lower torso toward the floor, then raise back to neutral. Do not hyperextend past a straight line.",
    commonPitfalls: "Hyperextending the lower back at the top. Rounding during the descent. Using too much weight before mastering bodyweight.",
  },
  {
    name: "Bird Dog",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["ABS"],
    description: "Quadruped stability drill; lower back endurance and balance.",
    instructions: "Start on all fours. Extend opposite arm and leg simultaneously while keeping the back flat. Hold 2–3 seconds. Alternate sides.",
    commonPitfalls: "Rotating the hips. Raising the leg too high. Losing core engagement and letting the back sag.",
  },

  // ─── Bands ────────────────────────────────────────────────────────────────
  {
    name: "Resistance Band Rows",
    equipment: "BAND",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["BICEPS"],
    description: "Portable pulling movement; back and arm development.",
    instructions: "Anchor band at waist height. Hold handles with underhand or neutral grip. Step back for tension. Row handles to abdomen, driving elbows back.",
    commonPitfalls: "Letting the band snap arms forward (control the return). Rocking the torso. Insufficient band tension making the movement too easy.",
  },
  {
    name: "Resistance Band Chest Press",
    equipment: "BAND",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS"],
    description: "Band pressing; variable resistance chest work.",
    instructions: "Anchor band behind you at chest height. Hold handles and step forward for tension. Press hands forward and slightly inward to full extension.",
    commonPitfalls: "Not stepping far enough forward for adequate resistance. Letting elbows drop below chest level. Releasing tension on the return.",
  },
  {
    name: "Resistance Band Curls",
    equipment: "BAND",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: [],
    description: "Band isolation for biceps; portable arm training.",
    instructions: "Stand on the middle of the band, hold handles underhand. Keeping upper arms stationary, curl handles to shoulder height. Lower slowly.",
    commonPitfalls: "Band slipping underfoot. Swinging the torso. Using too light a band and losing time under tension.",
  },
  {
    name: "Resistance Band Pull-aparts",
    equipment: "BAND",
    primaryMuscles: ["UPPER_BACK", "REAR_DELTS"],
    secondaryMuscles: [],
    description: "Band rear delt and back fly; shoulder health accessory.",
    instructions: "Hold band at chest height, arms extended. Pull band apart, squeezing shoulder blades. Return.",
    commonPitfalls: "Band too loose (insufficient tension). Moving arms too wide. Losing posture.",
  },
  {
    name: "Resistance Band Overhead Press",
    equipment: "BAND",
    primaryMuscles: ["FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS"],
    description: "Band overhead pressing; variable resistance shoulder work.",
    instructions: "Stand on band, hold handles at shoulders. Press overhead to full extension. Lower slowly.",
    commonPitfalls: "Band rolling off feet. Arching the lower back. Pressing forward instead of up.",
  },
  {
    name: "Resistance Band Face Pulls",
    equipment: "BAND",
    primaryMuscles: ["REAR_DELTS"],
    secondaryMuscles: ["UPPER_BACK"],
    description: "Rear delt and shoulder health movement; rotator cuff work.",
    instructions: "Anchor band at eye height. Pull band toward face, spreading hands apart. Squeeze shoulder blades.",
    commonPitfalls: "Band too loose. Not achieving full range. Using traps instead of rear delts.",
  },
  {
    name: "Resistance Band Lateral Walks",
    equipment: "BAND",
    primaryMuscles: ["ABDUCTORS", "GLUTES"],
    secondaryMuscles: ["QUADS"],
    description: "Banded lateral walk; hip abductor activation and glute work.",
    instructions: "Band around thighs just above knees. Slight crouch, step laterally keeping tension. Step for reps.",
    commonPitfalls: "Band slipping down. Knees rotating inward. Insufficient tension.",
  },

  // ─── Cardio ───────────────────────────────────────────────────────────────
  {
    name: "Treadmill",
    equipment: "MACHINE",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "HAMSTRINGS", "CALVES"],
    description: "Controlled running or walking; foundational cardiovascular training.",
    instructions: "Set speed and incline to match goal (easy jog: 50–60% max HR; tempo: 70–80%). Land mid-foot, maintain upright posture.",
    commonPitfalls: "Holding the handrails (reduces caloric burn and posture). Over-striding. Setting incline at 0% (increases knee impact vs. 1–2° natural incline).",
  },
  {
    name: "Stationary Bike",
    equipment: "MACHINE",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "HAMSTRINGS"],
    description: "Low-impact cardiovascular training; joint-friendly.",
    instructions: "Set seat height so knee has a slight bend at the bottom of the pedal stroke. Keep cadence 70–100 RPM for aerobic work.",
    commonPitfalls: "Seat too low (knee stress). Rocking the hips to generate power. Using arms instead of legs.",
  },
  {
    name: "Rowing Machine",
    equipment: "MACHINE",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["UPPER_BACK", "BICEPS", "QUADS"],
    description: "Full-body low-impact cardio; high caloric burn.",
    instructions: "Drive through legs first, then lean back slightly, then pull handle to lower chest. Return in reverse order: arms, body, legs.",
    commonPitfalls: "Pulling with arms before legs finish. Rounding the lower back. Seat hitting heels at the catch.",
  },
  {
    name: "Jump Rope",
    equipment: "OTHER",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["CALVES", "FRONT_DELTS"],
    description: "High-intensity cardiovascular exercise; coordination and footwork.",
    instructions: "Keep elbows close to the body, turn the rope with wrists. Land softly on the balls of both feet. Start with basic bounce before progressing to double-unders.",
    commonPitfalls: "Jumping too high (wastes energy). Using arms instead of wrists. Not warming up calves first.",
  },
  {
    name: "Stair Climber",
    equipment: "MACHINE",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "GLUTES"],
    description: "Stair-climbing machine; lower body and cardiovascular conditioning.",
    instructions: "Step at a pace that keeps HR in target zone. Stand tall and avoid leaning on the rails. Full step down for glute activation.",
    commonPitfalls: "Hanging on the handrails. Taking partial steps. Going too fast and losing form.",
  },
  {
    name: "Elliptical",
    equipment: "MACHINE",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "HAMSTRINGS"],
    description: "Low-impact elliptical motion; joint-friendly aerobic training.",
    instructions: "Keep resistance high enough to feel challenged. Push and pull the handles equally. Maintain an upright posture.",
    commonPitfalls: "Setting resistance too low and coasting. Leaning on handles. Not engaging the full stride.",
  },
  {
    name: "Battle Ropes",
    equipment: "OTHER",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["FRONT_DELTS", "ABS"],
    description: "High-intensity rope waves; upper body cardio and conditioning.",
    instructions: "Anchor ropes at a fixed point. Hold one end in each hand. Create alternating or simultaneous waves. Keep core tight and stance athletic.",
    commonPitfalls: "Standing too close to the anchor (reduces range). Losing core engagement. Waves dying out due to fatigue — reduce reps rather than losing form.",
  },
  {
    name: "Box Jumps",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "GLUTES"],
    description: "Plyometric jumping exercise; power, explosiveness, and cardio.",
    instructions: "Stand in front of a box. Dip into a quarter squat, swing arms, and jump onto the box. Land softly with knees bent. Step down (do not jump down from height).",
    commonPitfalls: "Jumping down from the box (Achilles injury risk). Landing with straight legs. Using a box that is too high before mastering the movement.",
  },
  {
    name: "High Knees",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "CALVES"],
    description: "Running in place with exaggerated knee drive; cardio and hip flexor activation.",
    instructions: "Drive each knee up to waist height alternately. Pump arms in opposition. Stay on the balls of your feet and keep a quick cadence.",
    commonPitfalls: "Leaning back. Knees not reaching hip height. Losing arm-leg coordination.",
  },
  {
    name: "Sled Push",
    equipment: "OTHER",
    primaryMuscles: ["CARDIO"],
    secondaryMuscles: ["QUADS", "GLUTES"],
    description: "Loaded sled push; power conditioning and metabolic training.",
    instructions: "Grip handles and drive forward with a forward lean. Push through the balls of your feet in a running motion. Maintain constant pressure on the sled.",
    commonPitfalls: "Hips rising and losing power transfer. Too much weight for the distance. Not leaning forward enough.",
  },
];

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set.");

  const prisma = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url }) });

  try {
    let created = 0;
    let updated = 0;
    for (const ex of SYSTEM_EXERCISES) {
      const existing = await prisma.exercise.findFirst({
        where: { name: ex.name, isSystem: true },
        select: { id: true },
      });
      if (existing) {
        await prisma.exercise.update({
          where: { id: existing.id },
          data: {
            description: ex.description ?? null,
            equipment: ex.equipment,
            primaryMuscles: ex.primaryMuscles,
            secondaryMuscles: ex.secondaryMuscles ?? [],
            instructions: ex.instructions ?? null,
            commonPitfalls: ex.commonPitfalls ?? null,
          },
        });
        updated += 1;
      } else {
        await prisma.exercise.create({
          data: {
            isSystem: true,
            ownerId: null,
            name: ex.name,
            description: ex.description ?? null,
            equipment: ex.equipment,
            primaryMuscles: ex.primaryMuscles,
            secondaryMuscles: ex.secondaryMuscles ?? [],
            instructions: ex.instructions ?? null,
            commonPitfalls: ex.commonPitfalls ?? null,
          },
        });
        created += 1;
      }
    }

    console.log(
      `Seed complete: ${created} system exercise(s) created, ` +
        `${updated} updated.`,
    );
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
